### PR TITLE
Switch CI and Docker to Fedora 33

### PR DESCRIPTION
**Pull request by morxa**

### CODE REVIEW

**Comment by morxa** [comment]
I fixed the compiler warnings in #97  but forgot to actually switch to Fedora 33 :)

**Comment by TarikViehmann** [comment]
when i try to build the docker i get

```
Error: Unable to find a match: libboost_system.so.1.69.0()(64bit) libboost_thread.so.1.69.0()(64bit) libprotobuf.so.17()(64bit)
Error: error building at STEP "RUN dnf install -y --nodocs $(cat /requires.txt) && dnf clean all && rm /requires.txt": error while running runtime: exit status 1
```

**Comment by morxa** [comment]
Yes, the problem is that we just copy everything into the container and then build. If you built the repo before, it won't properly rebuild in the container. Building the docker image only really works in a clean environment.

**Comment by TarikViehmann** [comment]
i actually ran make clean before building the docker :thinking:

**Review by TarikViehmann — APPROVED** [review]
Looks good. Thank you!

**Pull request merged**
